"""
Example script for question answering with Balorg AI.

Demonstrates various question answering capabilities.
"""

from balorg_ai.applications import QuestionAnsweringSystem
from balorg_ai.models import BalorgTransformer, ModelConfig


def main():
    print("Balorg AI Question Answering Example")
    print("=" * 50)
    
    # Create model configuration
    config = ModelConfig(
        vocab_size=50000,
        hidden_size=768,
        num_hidden_layers=12,
        num_attention_heads=12,
    )
    
    # Create model
    model = BalorgTransformer(config)
    print("Model created successfully!")
    
    # Dummy tokenizer
    class DummyTokenizer:
        def encode(self, text, return_tensors):
            import torch
            return torch.randint(0, config.vocab_size, (1, 100))
        
        def decode(self, tokens, skip_special_tokens=False):
            return "This is an answer generated by Balorg AI based on the question."
    
    tokenizer = DummyTokenizer()
    
    # Create Q&A system
    qa_system = QuestionAnsweringSystem(
        model=model,
        tokenizer=tokenizer,
    )
    
    print("\nQuestion Answering System initialized!\n")
    
    # Example 1: Basic question answering
    print("1. Basic Question Answering")
    print("-" * 50)
    question = "What is artificial intelligence?"
    answer = qa_system.answer_question(question)
    print(f"Q: {question}")
    print(f"A: {answer}\n")
    
    # Example 2: Context-based question answering
    print("2. Context-Based Question Answering")
    print("-" * 50)
    context = """
    Artificial Intelligence (AI) is the simulation of human intelligence processes 
    by machines, especially computer systems. These processes include learning, 
    reasoning, and self-correction. AI has applications in various fields including 
    healthcare, finance, and transportation.
    """
    question = "What are some applications of AI?"
    answer = qa_system.answer_question(question, context=context)
    print(f"Context: {context.strip()}")
    print(f"Q: {question}")
    print(f"A: {answer}\n")
    
    # Example 3: Multiple questions
    print("3. Multiple Questions")
    print("-" * 50)
    questions = [
        "What is machine learning?",
        "How does deep learning work?",
        "What is a neural network?",
    ]
    answers = qa_system.answer_multiple_questions(questions)
    for q, a in zip(questions, answers):
        print(f"Q: {q}")
        print(f"A: {a}\n")
    
    # Interactive mode
    print("=" * 50)
    print("\nStarting interactive Q&A mode...")
    print("Type 'exit', 'quit', or 'bye' to end.\n")
    qa_system.interactive_qa()


if __name__ == "__main__":
    main()
